import type { LucideIcon } from "lucide-react";
import {
  UtensilsCrossed,
  Car,
  ShoppingBag,
  Gamepad2,
  Receipt,
  Heart,
  BookOpen,
  Banknote,
  Briefcase,
  TrendingUp,
  Gift,
  PiggyBank,
  Coffee,
  Plane,
  Home,
  Monitor,
  Smartphone,
  Wifi,
  Zap,
  Droplets,
  Shirt,
  Scissors,
  Dumbbell,
  Stethoscope,
  Pill,
  Syringe,
  Baby,
  GraduationCap,
  Bus,
  Train,
  Ticket,
  Music,
  Video,
  Camera,
  Paintbrush,
  Hammer,
  Wrench,
  HelpCircle,
  Tag,
  CircleDollarSign,
  Landmark,
  Coins,
  CreditCard,
  Building2,
  Trophy,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "utensils-crossed": UtensilsCrossed,
  car: Car,
  "shopping-bag": ShoppingBag,
  "gamepad-2": Gamepad2,
  receipt: Receipt,
  heart: Heart,
  "book-open": BookOpen,
  banknote: Banknote,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  gift: Gift,
  "piggy-bank": PiggyBank,
  coffee: Coffee,
  plane: Plane,
  home: Home,
  monitor: Monitor,
  smartphone: Smartphone,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  shirt: Shirt,
  scissors: Scissors,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  baby: Baby,
  "graduation-cap": GraduationCap,
  bus: Bus,
  train: Train,
  ticket: Ticket,
  music: Music,
  video: Video,
  camera: Camera,
  paintbrush: Paintbrush,
  hammer: Hammer,
  wrench: Wrench,
  "help-circle": HelpCircle,
  tag: Tag,
  "circle-dollar-sign": CircleDollarSign,
  landmark: Landmark,
  coins: Coins,
  "credit-card": CreditCard,
  "building-2": Building2,
  trophy: Trophy,
};

export const CATEGORY_ICONS_BY_GROUP: Record<string, string[]> = {
  makanan: ["utensils-crossed", "coffee"],
  transportasi: ["car", "bus", "train", "plane"],
  belanja: ["shopping-bag", "shirt", "tag"],
  hiburan: ["gamepad-2", "music", "video", "ticket", "camera"],
  tagihan: ["receipt", "home", "zap", "droplets", "wifi", "smartphone", "monitor"],
  kesehatan: ["heart", "stethoscope", "pill", "syringe", "dumbbell"],
  pendidikan: ["book-open", "graduation-cap"],
  pemasukan: ["banknote", "coins", "circle-dollar-sign", "briefcase", "landmark", "building-2"],
  investasi: ["trending-up", "piggy-bank", "trophy"],
  lainnya: ["gift", "baby", "scissors", "paintbrush", "hammer", "wrench", "help-circle"],
};

export const DEFAULT_CATEGORY_ICON = "tag";

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Tag;
}
